### PR TITLE
Add Leeway Easy Configuration

### PR DESCRIPTION
**Pull request by anatolyD**
- overloaded factory method to add leeway configuration
- covered with unit test

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Thanks for the contribution. I don't know how regular this use-case scenario is tbh, but all the classes and methods involved in such modification are public so this can be easily achieved today without the need to create another static method. I don't want to keep adding methods for every possible combination of configuration values..

**Comment by anatolyD** [comment]
@lbalmaceda, i know i know. though this method covers one property of provider that can't be set without reinstantiating the whole thing. Leeway is the only not easily configurable thing
I think I have 3 projects where i have to repeat this provider init statments :( 
```   
           JwtWebSecurityConfigurer
                    .forRS256(apiAudience, issuer, makeLeewayProvider())
                    .configure(http)
 ...
 private JwtAuthenticationProvider makeLeewayProvider() {
        return new JwtAuthenticationProvider(new JwkProviderBuilder(issuer).build(), issuer, apiAudience)
                .withJwtVerifierLeeway(DEFAULT_LEEWAY);
    }
```

i think this, `leeway` configuration is a good option to have.

**Comment by anatolyD** [comment]
i take silence as a `no` then 😛

**Comment by lbalmaceda** [comment]
@anatolyD Apologies for the late response I was on holidays. I'll consider a configuration object helper for a future version but today I don't think it's necessary. Thanks again!

**Pull request closed without merging**
