### PR TITLE
Upgrade to Spring Security 6, requiring Java 17 and Gradle 7.3 minimum

### PR DESCRIPTION
**Pull request by adrogon**
Upgrades the library to be compatible with Spring Security 6.

- Requires Java 17
- Upgrades Gradle to latest, 7.6 (minimum supported is 7.3)
- Upgrades Servlet API to 6, up from 2.5 (From Java EE to Jakarta EE)
- Upgrades other libraries to latest version
- Changes the CI pipeline to use the convenience images from CircleCI, and upgrade to OpenJDK 17

Please notice `jcenter()` was added to the list of repositories. It is deprecated, but so is Bintray.

### CODE REVIEW

**Comment by AlexanderNZ** [comment]
I'm currently blocked on updating to spring boot 3 and this PR would solve that blocker. Appreciate it's only been open two days but it would be great to get some feedback on timelines for review and merging of this PR.

**Comment by epiard13** [comment]
> Upgrades the library to be compatible with Spring Security 6.
> 
> * Requires Java 17
> * Upgrades Gradle to latest, 7.6 (minimum supported is 7.3)
> * Upgrades Servlet API to 6, up from 2.5 (From Java EE to Jakarta EE)
> * Upgrades other libraries to latest version
> * Changes the CI pipeline to use the convenience images from CircleCI, and upgrade to OpenJDK 17
> 
> Please notice `jcenter()` was added to the list of repositories. It is deprecated, but so is Bintray.

@adrogon Do you need to add a different Auth0 reviewer? It doesn't look like the current reviewer exists....
@jimmyjames Please advise...

**Comment by adrogon** [comment]
@epiard13 I don't know if Auth0 intends to maintain this library going forward. It was already disclaimed to not use it for Spring Security 5 anymore, so maybe it won't support Spring Security 6 at all?
But if they want to, well this PR is the beginning of an answer.

Please notice there is already a more recent version of Spring Security, but I'll wait for more information before updating this branch.

**Comment by jimmyjames** [comment]
Hey all, as noted we recommend using Spring Security directly now, as the framework has very good OAuth2 and OIDC support. If we do decide to update this library for Spring 6, this PR can be a good starting point, so thank you! 

With regards to Spring Security 6, we will be updating our quickstarts and samples for Spring 6. Until published, we've captured [an issue](https://github.com/auth0-samples/auth0-spring-security5-api-sample/issues/25) with steps to take to integrate authorization into your application using Spring Security 6. If you have questions or run into issues with Spring 6, please chime in there. Thanks!

**Pull request closed without merging**
